workspace:
  base: /workspace
  path: src/github.com/bitlogic/demo-vote
pipeline:
  publish-vote-dockerhub:
    image: plugins/docker
    repo: bitlogicos/demo-vote
    tag:
    - latest
    - "1.0.${DRONE_BUILD_NUMBER}"
  deploy-to-party:
      image: plugins/ssh
      host: prod.bitlogic.party
      user: ec2-user
      port: 22
      script:
        - docker pull bitlogicos/demo
        - docker run --rm -v /var/run/docker.sock:/var/run/docker.sock bitlogicos/demo pull
        - docker run --rm -v /var/run/docker.sock:/var/run/docker.sock bitlogicos/demo